language: python
sudo: required
services:
  - docker
before_install:
    - docker build -t minhpro332/capstone .
script:
    - docker run -d -p 8000:8000 minhpro332/capstone
after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push minhpro332/capstone

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: my-capstone
  env: MyCapstone-env
  bucket_name: elasticbeanstalk-ap-southeast-1-792974750178
  bucket_path: my-capstone
  on:
    branch: feature/dockerized
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY